In [10]:
import pandas as pd


In [16]:
import numpy as np

In [18]:
import urllib.request

In [19]:
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x17324319890>)

In [21]:
climate_data=np.genfromtxt('climate.txt',delimiter=',', skip_header=1)

In [22]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [23]:
weights=np.array([0.3,0.2,0.5])

In [24]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
#we have climate_data:temperature,rainfall,humility .will will find yield and climate results.

In [25]:
yields=climate_data@weights

In [26]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [ ]:
#we will join 2 matrix togather and make  1 climate result matrix

In [33]:
climate_results=np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [34]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [38]:
saved_df=np.savetxt("climate_results.txt",climate_results,header="humility,rainfall,temperature,yields",delimiter=",")